- src/ds/content/content_model.cpp
- src/ds/content/content_query.cpp
* Also improve printTree output to show names of resource properties
> Content query: Don't crash if child-parent relationship not configured

- src/ds/ui/sprite/text.cpp
* Without this fix, the Text sprite letter-spacing setting only works with integer values
> Fix floating-point letterspacing configuration for Text sprites

- src/ds/content/content_model.cpp
Previously it was only comparing the pointer values for resources, and not doing a full equality compare on their contents.
> [B] Correct contentProperty comparison for resources

- src/ds/ui/sprite/shader/sprite_shader.cpp
* If a shader file named Use <shader-name>.geom exists, DsCinder will use that in addition to the .frag and .vert files
> Add geometry shader support

- projects/essentials/src/ds/ui/sprite/line.cpp
Before, the line would calculate its distance as a function of its number of points. Since there's no guarantee that those points will be evenly distanced from each other, that meant animating the line by setting the end percentage would draw the line at variable speeds, making it speed up and slow down even with linear timing. This change makes the line consider it's total distance instead, making animations tween as expected.
The downside is that it adds an extra loop and distance calculations, which may affect performance. But I believe it's worth it to enable sensible tweening for line-drawing effects.
I've tested this PR with the boise state world museum repository, the only other project that uses the line sprite directly (as far as Luke or I could find), and it works!
> Refactor line distance calculation to handle tween values when animating

- doc/basics/Dynamic Interfaces.md
While developing, I noticed that the `media_player` layout won't respect options such as `media_player_auto_start` or `media_player_loop` unless the attribute `media_player_src` is placed last. This wasn't reflected in the docs, so I thought I would add a note to call this out.
> Adds note about order of media_player attributes

- src/ds/cfg/settings.cpp
- src/ds/cfg/settings.h
- src/ds/cfg/settings_variables.cpp
Previously. calling a setting in app via mEngine.getAppSettings() would not work correctly if the value contained an expression.
I'm not sure if this the best place to go through and replace variables and expressions, but I currently have it going through all the setting values after the variable map has been created in SettingVariables.
> Replace setting variables and expressions after variable map is created

- doc/basics/Dynamic Interfaces.md
- projects/essentials/src/ds/ui/interface_xml/interface_xml_importer.cpp
- projects/essentials/src/ds/ui/layout/smart_layout.cpp
This update allows the on_click_event and on_tap_event to access the data model via the sprites ds::UserData object. 
The 'model' property of a sprite will now drop a value into the UserData object when it detects an underscore before the property name:
`model="_type:this->sensor_type"`
will insert the value of the model property 'sensor_type' into the UserData object with the key '_type'
Correspondingly, the user_data parameter given to an event value will retrieve a value from the UserData object using the given key and put it in the mUserStringData property of the event:
{SelectSensorEvent; user_data:_type} 
Note that the key value given doesn't have to start with an underscore, so it can get strings out of the UserData object that were put there by other means.
> Add ability to push to UserData with 'model' property and pull with 'on_click_event' (or 'on_tap_event')

- projects/essentials/src/ds/ui/sprite/line.cpp
- projects/essentials/src/ds/ui/sprite/line.h
* Adds registration of the LineSprite at the top of its own file for netsync purposes. Before, you had to register the LineSprite in your projects for it to sync. Now, you don't have to worry about it.
* Adds a new method to the LineSprite, `getPointAtPercentage`. This was useful for me when doing the snake line easter egg, as I have to be able to get a point on the line at a certain percentage to know whether the line has collided with the dots it consumes.
* To test the netsyncing, I cloned a new DSCinder app and added a quick config for clientserver & client. I also added some code that creates a LineSprite and continually animates it. I was able to reproduce the issue without the fix, and verified that the issue is gone with the fix in place. You can find that [test repo bundled …
> adds new method to LineSprite and registers it for netsync

- src/ds/ui/sprite/sprite.cpp
I found a couple of issues in sprite::setFinalRenderToTexture while working on my warping sprite.
* The FBO's were never being cleared, which was leading to display artifacts.
* When rendering multiple sprites in the same tree to FBOs, the old drawing code did not correctly switch back to the original FBO. (e.g. Parent renders to an FBO, and a child renders to another FBO. Once the child has rendered, the parents FBO is not reactivated for drawing)
I believe the attached commits fix both of the above issues, but I think it needs wider testing before merging to master. Any apps you can think of that make use of rendering sprites to FBOs through setFinalRenderToTexture are good candidates for testing.
> Fixes for sprite::setFinalRenderToTexture()

- example/full_starter/settings/engine.xml
- src/ds/app/app.cpp
- src/ds/app/app.h
- src/ds/app/engine/engine_settings.cpp
Previously, if a DS Cinder app was set to fullscreen (by pressing "f", for instance), and the display was disconnected and reconnected, the app would lose its fullscreen status, requiring the user to press "f" again.
This PR adds a setting in the engine file called `"resetup_server_on_display_change"`. If true, the app will resetup the server when it detects a display change, maintaining the fullscreen status of the app even through disconnects.
NOTE: I set the default for this engine variable to false to be prudent, I guess. I could see a case for leaving it on true, so let me know if you want to change that.
* Copy the full_starter project from the repo (I've already add the new engine variable to engine.xml)
* Change the world dimensions to something smaller than your screen (to verify …
> Resetups server on display change

- example/full_starter/settings/engine.xml
- src/ds/app/app.cpp
- src/ds/app/engine/engine_settings.cpp
* I identified a logic gap for this variable where the flag would not revert to false if the variable in the engine.xml file was updated
* Changed the default for this variable to true
* Load up the new full starter (now has the `resetup_server_on_display_change` variable set to true by default)
* With the app loaded, set the above variable to false
* disconnect your monitor and reconnect it. Observe that the app does not resetup.
> Sets default for resetup on display change to true and fixes logic gap

- src/ds/app/engine/engine.cpp
- src/ds/app/engine/engine.h
- src/tuio/TuioClient.cpp
This fixes an existing bug when trying to reconnect to tuio after disconnecting it.
Previously, when reconnecting to tuio after disconnecting it - move and end touch events were not correctly recognized, resulting in stuck touches.
This fix converts the tuio client to a pointer, and creates and destroys the client on engine to ensure that touch callbacks get unregistered.
This also separates the start/stop tuio bits into separate functions outside of setupTouch.
> Fix tuio reconnect

- src/ds/ui/layout/layout_sprite.cpp
layout type horiz_wrap (vert_wrap) currently uses the parent's container's height (width) instead of the largest child's height (width). This should fix that if this is even something to be fixed. I feel like this has lots of potential to break other projects so I'm open to other solutions.
> changed horiz/vert _wrap layout sprite to get correct(?) height.

- src/ds/app/engine/engine_client.cpp
- src/ds/app/engine/engine_io.cpp
- src/ds/app/engine/engine_io.h
- src/ds/app/engine/engine_server.cpp
This resolves an issue where servers would give up too easily if they hadn't gotten a packet back from the client.
> EngineServer: resolve an issue where servers and clients weren't talking

- src/ds/content/content_model.cpp
- src/ds/content/content_model.h
Adds maps of contentModelRefs to each content model for easily handling links, look ups, references or other things that aren't a strict hierarchy or would require faster lookups.
> ContentModel: Add reference maps

- projects/video/gstreamer-1.0/src/ds/ui/sprite/panoramic_video.cpp
- projects/video/gstreamer-1.0/src/ds/ui/sprite/panoramic_video.h
- projects/viewers/src/ds/ui/media/player/panoramic_video_player.cpp
Currently the panoramic video player has a video interface but once it auto-hides there is no way to get it back. This makes it so that any touch that moves less than the minimum tap distance triggers the interface to reappear.
> Tapping panoramic video player opens the media interface

- src/ds/ui/sprite/text.h
Added getFitFontSize to get the font size that is the result of a fit_to_limit text sprite.
Changed mPangoContext and mPangoLayout to be protected so that subclasses calling the protected measurePangoText can get the results of said operation.
> Added getFitFontSize. Changed mPangoContext and mPangoLayout visibility

- src/ds/content/content_model.cpp
- src/ds/content/content_model.h
Adds setters and getters for list types of all common properties. For example:
```
mModel.addPropertyToList("prop_name", "a_property");
mModel.addPropertyToList("prop_name", "another_property");
for(auto it : mModel.getPropertyListString("prop_name"){
std::cout << "prop: " << it << std::endl;
};
//output:
prop: a_property
prop: another_property
```
> ContentModel: Add list abilities for properties

- doc/basics/Dynamic Interfaces.md
- projects/essentials/src/ds/ui/interface_xml/interface_xml_importer.cpp
- projects/essentials/src/ds/ui/layout/smart_layout.cpp
- projects/essentials/src/ds/ui/layout/smart_layout.h
Changes src/filename property and resource model target to accept image loading flags a __flag_. This makes the change backward compatible with src_cache and resource_cache.
examples:
`<image src_cache="%APP%/data/images/super.png"/>` - caches the image.
`<image src_mipmap="%APP%/data/images/super.png"/>`- adds mipmaps for the image.
`<image src_cache_mipmap="%APP%/data/images/super.png"/>`- cahces and mipmaps the image.
`<image src_c_m="%APP%/data/images/super.png"/>`- same as above but shorthand syntax.
flags:
_cache/_c
_mipmap/_m
_skipmeta/_s
_preload/_p
> Added ability to set image loading flags from layout xml.

- projects/essentials/src/ds/ui/interface_xml/interface_xml_importer.cpp
Xml tag had reversed logic for target= property.
> Small fix to xml importer. 

- doc/basics/Dynamic Interfaces.md
- projects/essentials/src/ds/ui/interface_xml/interface_xml_importer.cpp
This changes the huge if/else chain into an unordered map. The speed improvements are negligible, but it should set things up for easier maintainability and feature improvements
> XmlImporter: refactor sprite setting to use a map

- doc/basics/Dynamic Interfaces.md
- src/ds/ui/sprite/sprite.cpp
- src/ds/ui/sprite/sprite.h
- src/ds/ui/sprite/util/blend.cpp
- src/ds/ui/sprite/util/blend.h
I added the option to set the FBO format when setting a sprite as finalRenderToTexture, so now we're able to tune the antialiasing and other texture properties.
I also added a blend mode for premultiplied-alpha drawing, which is needed to remove the dark halo effect created when drawing semi-transparent images into an FBO.
> FBO rendering fixes

- projects/video/gstreamer-1.0/src/gstreamer/gstreamer_env_check.cpp
This should allow gstreamer to successfully create a plugin registry in the application root. Should still respect GST_REGISTRY_1_0 environment variable if it exists. If it is working you will have a file called .gstcache in the application directory. (same directory as /data and /settings
> GStreamer Registry Path fix

- projects/essentials/src/ds/ui/sprite/png_sequence_sprite.cpp
- projects/essentials/src/ds/ui/sprite/png_sequence_sprite.h
During the PwC Global project, I found it useful to have an "animation ended" callback that we could call to trigger certain things throughout the app. I also found that the PngSequenceSprite images take a while to all load their frames and sometimes trying to do something with them before they've loaded everything can be bad, so I added an `isLoaded()` method to the class. To take that a step further, I added a callback that is called the moment that state changes. This could be used to do things like change the state of a parent or trigger actions elsewhere.
Apologies for the autoformatting.
> [F] Added loaded state/callback and animation ended callback.

- projects/video/gstreamer-1.0/src/ds/ui/sprite/panoramic_video.cpp
- projects/video/gstreamer-1.0/src/ds/ui/sprite/panoramic_video.h
- projects/viewers/src/ds/ui/media/player/panoramic_video_player.cpp
- projects/viewers/src/ds/ui/media/player/panoramic_video_player.h
Updates to panoramic video player so that the shader geometry can be flipped on instantiation in the special snowflake case of P57 Terrace Photo Opp, whereby the app needs to display a spherical video stream, but mirror it because it is a photobooth preview. Should be innocuous behavior to code predating this change.
> Pano cam updates tsd
